"use client";

import Link from "next/link";
import { useEffect, useRef, useState, type ChangeEvent, type FormEvent, type ReactNode } from "react";
import PublicIcon from "@/components/icons/PublicIcon";
import { Toast } from "@/components/ui";

const steps = ["Basic Information", "Pricing", "Product Files", "License & Access", "Review & Publish"] as const;
type Props = { productsPath: string; storefrontName: string };
type StepProps = { productType: string; setProductType: (value: string) => void };
const input = "mt-1.5 h-9 w-full rounded-lg border border-border-control bg-white px-3 text-xs text-body outline-none placeholder:text-muted-faint focus:border-primary";
const select = `${input} select-chevron`;
const dropdownSelect = `${input} appearance-none select-chevron`;

export default function AddProductForm({ productsPath, storefrontName }: Props) {
  const [step, setStep] = useState(0);
  const [status, setStatus] = useState<"Draft" | "Published">("Draft");
  const [productType, setProductType] = useState("Digital Download");
  const [freeProduct, setFreeProduct] = useState(false);
  const [files, setFiles] = useState<string[]>([]);
  const [notice, setNotice] = useState(false);
  const stepRefs = useRef<Array<HTMLDivElement | null>>([]);
  const visibleSteps = freeProduct ? steps.filter((label) => label !== "License & Access") : steps;
  const handleFiles = (event: ChangeEvent<HTMLInputElement>) => setFiles(Array.from(event.target.files ?? []).map((file) => file.name));
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setNotice(true); };

  useEffect(() => {
    stepRefs.current[step]?.scrollIntoView({ behavior: "smooth", block: "nearest", inline: "center" });
  }, [step]);

  return <form onSubmit={submit} className="relative">
    {notice && <Toast variant="success" message={status === "Published" ? "Your product is now published." : "Your product has been saved as a draft."} onClose={() => setNotice(false)} />}
    <div className="mb-2 flex items-center justify-between">
      <p className="text-[10px] font-semibold uppercase tracking-[0.08em] text-muted">Product setup</p>
      <p className="text-[10px] font-semibold text-primary">Step {step + 1} of {visibleSteps.length}</p>
    </div>
    <nav className="scrollbar-hidden mb-5 flex min-w-0 snap-x items-center overflow-x-auto pb-2" aria-label="Product creation steps">
      {visibleSteps.map((label, index) => {
        const active = index === step;
        const complete = index < step;
        return (
          <div ref={(element) => { stepRefs.current[index] = element; }} key={label} className="flex min-w-[9.25rem] snap-start items-center sm:min-w-0 sm:flex-1">
            <button
              type="button"
              disabled={index > step}
              aria-current={active ? "step" : undefined}
              onClick={() => setStep(index)}
              className={`group flex min-w-max items-center gap-1.5 text-[9px] transition sm:text-[10px] ${active ? "font-semibold text-primary" : complete ? "font-medium text-status-success" : "text-muted"}`}
            >
              <span className={`grid h-5 w-5 shrink-0 place-items-center rounded-full border text-[9px] font-bold ${active ? "border-primary bg-primary text-white" : complete ? "border-status-success bg-status-success text-white" : "border-border bg-surface-control text-muted"}`}>
                {complete ? <PublicIcon name="check" className="h-3 w-3" /> : index + 1}
              </span>
              <span>{label}</span>
            </button>
            {index < visibleSteps.length - 1 && <span className={`mx-2 h-px min-w-3 flex-1 ${complete ? "bg-status-success" : "bg-border"}`} aria-hidden="true" />}
          </div>
        );
      })}
    </nav>
    {step === 1 && <label className={`mb-4 flex cursor-pointer items-start gap-3 rounded-xl border p-4 transition ${freeProduct ? "border-primary bg-accent-light" : "border-border bg-white hover:border-primary/50 hover:bg-surface-hover"}`}><input type="checkbox" checked={freeProduct} onChange={(event) => setFreeProduct(event.target.checked)} className="mt-0.5 h-5 w-5 shrink-0 accent-primary" /><span><span className="block text-sm font-bold text-heading">This is a free product</span><span className="mt-1 block text-[11px] font-normal leading-4 text-muted">Customers can access it for free. License and paid pricing steps will be skipped.</span></span></label>}
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_280px]">
      <div className="min-w-0 rounded-2xl border border-border bg-white p-5 shadow-sm sm:p-6">
        {visibleSteps[step] === "Basic Information" && <BasicInformation productType={productType} setProductType={setProductType} />}
        {visibleSteps[step] === "Pricing" && (freeProduct ? <FreePricing /> : <Pricing />)}
        {visibleSteps[step] === "Product Files" && <ProductFiles files={files} onFiles={handleFiles} />}
        {visibleSteps[step] === "License & Access" && <LicenseAccess />}
        {visibleSteps[step] === "Review & Publish" && <ReviewProduct files={files} productType={productType} storefrontName={storefrontName} freeProduct={freeProduct} />}
        <div className="mt-6 flex items-center justify-between border-t border-divider pt-5"><Link href={productsPath} className="rounded-lg border border-border-control px-3.5 py-2 text-xs font-medium text-muted no-underline hover:bg-surface-control">Cancel</Link><div className="flex gap-2">{step > 0 && <button type="button" onClick={() => setStep((value) => value - 1)} className="rounded-lg border border-border-control px-3.5 py-2 text-xs font-medium text-body hover:bg-surface-control">Back</button>}{step < visibleSteps.length - 1 ? <button type="button" onClick={() => setStep((value) => value + 1)} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-xs font-semibold text-white hover:bg-primary-hover">Next <PublicIcon name="right" className="h-3 w-3" /></button> : <button type="submit" className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-xs font-semibold text-white hover:bg-primary-hover">{status === "Published" ? "Publish" : "Save Draft"} <PublicIcon name="check" className="h-3.5 w-3.5" /></button>}</div></div>
      </div>
      <aside className="space-y-5"><section className="rounded-2xl border border-border bg-white p-5 shadow-sm"><h2 className="text-sm font-bold text-heading">Product Status</h2><div className="mt-4 space-y-3">{(["Draft", "Published"] as const).map((option) => <label key={option} className="flex cursor-pointer items-start gap-2 text-xs text-body"><input type="radio" name="status" checked={status === option} onChange={() => setStatus(option)} className="mt-0.5 accent-primary" /><span><strong>{option}</strong><span className="mt-1 block text-[10px] text-muted-soft">{option === "Draft" ? "Saved privately until you publish." : "Visible to customers after publishing."}</span></span></label>)}</div></section><section className="rounded-2xl border border-border bg-white p-5 shadow-sm"><h2 className="text-sm font-bold text-heading">Tips</h2><ul className="mt-3 space-y-2 text-[10px] leading-4 text-muted"><li>Use a clear and descriptive title.</li><li>Add high-quality product files.</li><li>Set a fair price and license.</li><li>Review everything before publishing.</li></ul></section></aside>
    </div>
  </form>;
}

function Title({ title, description }: { title: string; description: string }) { return <div><h2 className="text-base font-bold text-heading">{title}</h2><p className="mt-1 text-xs text-muted">{description}</p></div>; }
function Field({ label, children, required = false }: { label: string; children: ReactNode; required?: boolean }) { return <label className="block text-[11px] font-semibold text-body">{label}{required && <span className="text-status-danger"> *</span>}{children}</label>; }

function BasicInformation({ productType, setProductType }: StepProps) { return <section><Title title="Basic Information" description="Add the basic details of your product." /><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Product Title" required><input required name="title" placeholder="e.g. Laravel API Mastery" className={input} /></Field><Field label="Product Slug"><input name="slug" placeholder="laravel-api-mastery" className={input} /></Field><Field label="Short Description" required><textarea required name="description" rows={3} placeholder="A short summary of your product" className="mt-1.5 w-full resize-y rounded-lg border border-border-control px-3 py-2 text-xs outline-none focus:border-primary sm:col-span-2" /></Field><Field label="Category" required><select required name="category" defaultValue="" className={select}><option value="" disabled>Select category</option><option>Development</option><option>Design</option><option>Marketing</option></select></Field><Field label="Subcategory"><select name="subcategory" defaultValue="" className={select}><option value="" disabled>Select subcategory</option><option>Backend Development</option><option>Frontend Development</option><option>UI Design</option></select></Field></div><Field label="Tags"><input name="tags" placeholder="laravel, api, rest, backend" className={input} /></Field><Field label="Product Description" required><textarea required name="longDescription" rows={7} placeholder="Describe what customers will learn or receive..." className="mt-1.5 w-full resize-y rounded-lg border border-border-control px-3 py-2 text-xs outline-none focus:border-primary" /></Field><fieldset className="mt-5"><legend className="text-[11px] font-semibold text-body">Product Type</legend><div className="mt-2 grid gap-3 sm:grid-cols-3">{["Digital Download", "Online Course", "License / Key"].map((type) => <label key={type} className={`flex cursor-pointer gap-2 rounded-lg border p-3 text-[10px] ${productType === type ? "border-primary bg-accent-light" : "border-border-control"}`}><input type="radio" name="productType" checked={productType === type} onChange={() => setProductType(type)} className="mt-0.5 accent-primary" /><span><strong className="block">{type}</strong><span className="mt-1 block text-[9px] font-normal text-muted-soft">{type === "Digital Download" ? "Files customers can download" : type === "Online Course" ? "Video lessons and materials" : "Software license or key"}</span></span></label>)}</div></fieldset></section>; }
function FreePricing() { return <section><Title title="Pricing" description="This product will be available at no cost to customers." /><div className="mt-5 rounded-xl border border-status-success/20 bg-status-success-surface p-5"><p className="text-xs font-semibold text-status-success">Free product</p><p className="mt-2 text-2xl font-bold text-heading">$0.00</p><p className="mt-1 text-[10px] text-muted">Customers can download this product without payment.</p></div><div className="mt-5 grid gap-4 border-t border-divider pt-5 sm:grid-cols-2"><Field label="Currency"><Dropdown name="currency"><option>USD - US Dollar</option><option>KHR - Cambodian Riel</option></Dropdown></Field><Field label="Tax"><Dropdown name="tax"><option>No Tax</option><option>Standard Tax</option></Dropdown></Field></div></section>; }
function Pricing() { return <section><Title title="Pricing" description="Set the price and discount for your product." /><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Price" required><input required name="price" type="number" min="0" step="0.01" placeholder="0.00" className={input} /></Field><Field label="Compare at Price"><input name="compareAtPrice" type="number" min="0" step="0.01" placeholder="0.00" className={input} /></Field></div><fieldset className="mt-5"><legend className="text-[11px] font-semibold text-body">Discount Type</legend><div className="mt-3 space-y-3 text-xs text-body"><label className="flex items-center gap-2"><input type="radio" name="discount" defaultChecked className="accent-primary" /> No Discount</label><label className="flex items-center gap-2"><input type="radio" name="discount" className="accent-primary" /> Percentage <input type="number" min="0" max="100" placeholder="0" className="h-8 w-24 rounded-lg border border-border-control px-2 text-xs" />%</label><label className="flex items-center gap-2"><input type="radio" name="discount" className="accent-primary" /> Fixed Amount <input type="number" min="0" placeholder="0.00" className="h-8 w-24 rounded-lg border border-border-control px-2 text-xs" /></label></div></fieldset><div className="mt-6 grid gap-4 border-t border-divider pt-5 sm:grid-cols-2"><Field label="Currency"><Dropdown name="currency"><option>USD - US Dollar</option><option>KHR - Cambodian Riel</option></Dropdown></Field><Field label="Tax"><Dropdown name="tax"><option>No Tax</option><option>Standard Tax</option></Dropdown></Field></div><div className="mt-5 rounded-lg border border-status-info/20 bg-status-info-surface p-4"><p className="text-xs font-semibold text-status-info">Your Earnings</p><p className="mt-1 text-xl font-bold text-heading">$31.20</p><p className="mt-1 text-[10px] text-muted">Estimated after marketplace fees.</p></div></section>; }
function Dropdown({ name, children, required = false, defaultValue }: { name: string; children: ReactNode; required?: boolean; defaultValue?: string }) { return <span className="mt-1.5 block"><select name={name} required={required} defaultValue={defaultValue} className={`${dropdownSelect} mt-0 pr-9 focus:ring-2 focus:ring-orange-100`}>{children}</select></span>; }
function ProductFiles({ files, onFiles }: { files: string[]; onFiles: (event: ChangeEvent<HTMLInputElement>) => void }) { return <section><Title title="Product Files" description="Upload the files customers will receive after purchase." /><label className="mt-5 flex min-h-48 cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed border-border-control bg-surface-muted p-6 text-center hover:border-primary hover:bg-surface-hover"><PublicIcon name="download" className="h-8 w-8 text-primary" /><strong className="mt-3 text-xs text-body">Drag & drop your files here</strong><span className="mt-1 text-[10px] text-muted-soft">or choose files from your computer</span><span className="mt-4 rounded-lg border border-primary px-4 py-2 text-[10px] font-semibold text-primary">Upload Files</span><input type="file" multiple onChange={onFiles} className="sr-only" /></label>{files.length > 0 && <div className="mt-5 rounded-xl border border-border p-4"><p className="text-xs font-semibold text-heading">Uploaded Files ({files.length})</p><ul className="mt-3 space-y-2">{files.map((file) => <li key={file} className="flex items-center gap-2 rounded-lg bg-surface-muted px-3 py-2 text-[10px] text-body"><PublicIcon name="file-search-corner" className="h-4 w-4 text-primary" />{file}</li>)}</ul></div>}</section>; }
function LicenseAccess() { return <section><Title title="License & Access" description="Choose how customers can use this product." /><div className="mt-5 grid gap-5 sm:grid-cols-2"><Field label="License Type" required><select required name="license" defaultValue="" className={select}><option value="" disabled>Select license</option><option>Standard License</option><option>Personal License</option><option>Commercial License</option></select></Field><Field label="Access Type"><select name="access" className={select}><option>Lifetime Access</option><option>Limited Access</option><option>Subscription</option></select></Field></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="rounded-xl border border-primary bg-accent-light p-4"><p className="text-xs font-semibold text-heading">Standard License</p><p className="mt-1 text-[10px] text-muted">For personal and commercial use.</p><ul className="mt-3 space-y-1.5 text-[10px] text-body"><li>✓ One user / single project</li><li>✓ No redistribution</li><li>✓ Support via email</li></ul></div><div className="space-y-4"><label className="flex items-start gap-2 text-xs text-body"><input type="radio" name="accessRule" defaultChecked className="mt-0.5 accent-primary" /><span><strong className="block">Lifetime access</strong><span className="text-[10px] text-muted-soft">One-time purchase, unlimited access.</span></span></label><label className="flex items-start gap-2 text-xs text-body"><input type="radio" name="accessRule" className="mt-0.5 accent-primary" /><span><strong className="block">Limited downloads</strong><span className="text-[10px] text-muted-soft">Set a maximum download count.</span></span></label><Field label="Download limit"><input type="number" min="1" placeholder="5" className={input} /></Field></div></div></section>; }
function ReviewProduct({ files, productType, storefrontName, freeProduct }: { files: string[]; productType: string; storefrontName: string; freeProduct: boolean }) { return <section><Title title="Review & Publish" description="Review the details before publishing your product." /><div className="mt-5 space-y-4"><ReviewBlock title="Basic Information"><ReviewRow label="Product Title" value="Laravel API Mastery" /><ReviewRow label="Category" value="Development / Backend Development" /><ReviewRow label="Storefront" value={storefrontName} /><ReviewRow label="Product Type" value={productType} /></ReviewBlock><ReviewBlock title="Pricing"><ReviewRow label="Price" value={freeProduct ? "$0.00 (Free)" : "$39.00"} /><ReviewRow label="Compare at Price" value={freeProduct ? "Not applicable" : "$49.00"} /><ReviewRow label="Discount" value={freeProduct ? "Not applicable" : "20%"} /></ReviewBlock><ReviewBlock title={`Product Files (${files.length || 2})`}><ReviewRow label="Files" value={files.length ? files.join(", ") : "laravel-api-mastery.zip, api-documentation.pdf"} /></ReviewBlock>{!freeProduct && <ReviewBlock title="License & Access"><ReviewRow label="License Type" value="Standard License" /><ReviewRow label="Access" value="Lifetime Access" /></ReviewBlock>}</div></section>; }
function ReviewBlock({ title, children }: { title: string; children: ReactNode }) { return <div className="rounded-xl border border-border bg-surface-muted p-4"><h3 className="text-xs font-bold text-heading">{title}</h3><div className="mt-3 space-y-2">{children}</div></div>; }
function ReviewRow({ label, value }: { label: string; value: string }) { return <div className="grid gap-1 text-[10px] sm:grid-cols-[150px_1fr]"><span className="text-muted">{label}</span><strong className="text-body">{value}</strong></div>; }