import Link from "next/link";
import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import PublicFooter from "@/components/PublicFooter";
import PublicIcon from "@/components/icons/PublicIcon";
import StorefrontCartButton from "@/components/StorefrontCartButton";

const product = { name: "Startup Landing Page", type: "Template", price: "$24", oldPrice: "$39", icon: "landing" };
type Props = { params: Promise<{ storefrontName: string; productSlug: string }> };

export async function generateMetadata(): Promise<Metadata> { return { title: product.name, description: "A modern and responsive landing page template for startups, apps and digital products." }; }

export default async function ProductDetailPage({ params }: Props) {
  const { storefrontName } = await params;
  const name = decodeURIComponent(storefrontName);
  const basePath = `/marketplace/${encodeURIComponent(storefrontName)}`;
  const productPath = `${basePath}/startup-landing-page`;

  return <main className="min-h-screen bg-[#f7f9fd] text-[#142b4d]"><Navbar active="products" /><div className="mx-auto max-w-[1280px] px-4 pb-12 pt-5 sm:px-6 lg:px-8">
    <div className="flex items-center gap-2 text-[10px] text-slate-500"><Link href="/marketplace" className="text-indigo-500">⌂　Marketplace</Link><span>›</span><Link href={basePath} className="text-indigo-500">Templates</Link><span>›</span><b className="text-slate-700">{product.name}</b></div>
    <div className="mt-5 grid gap-6 xl:grid-cols-[minmax(0,1.28fr)_minmax(330px,.9fr)_275px]">
      <section><div className="rounded-xl border border-[#e5ebf4] bg-white p-3 shadow-sm"><div className="grid min-h-[390px] place-items-center rounded-lg bg-[#f5f7fc] p-6"><div className="product-art landing relative grid aspect-[1.52/1] w-full place-items-center overflow-hidden rounded-lg shadow-sm"><div className="absolute left-[10%] top-[17%] max-w-[47%]"><span className="text-[10px] font-bold text-primary">⚡ StartUp</span><p className="mt-8 text-xs text-indigo-500">Build Your Dream</p><h2 className="mt-1 text-2xl font-extrabold leading-tight text-[#102d55]">Startup <span className="text-primary">Faster</span></h2><p className="mt-2 text-[9px] leading-4 text-slate-500">The modern landing page template for startups, apps and digital products.</p><button type="button" className="mt-4 rounded bg-primary px-3 py-2 text-[8px] font-bold text-white">Get Started →</button></div><div className="absolute bottom-[12%] right-[9%] h-[48%] w-[43%] rounded-xl border-[6px] border-slate-800 bg-gradient-to-br from-slate-700 to-slate-950 p-4 shadow-xl"><div className="space-y-2"><i className="block h-1.5 w-2/3 rounded bg-blue-300" /><i className="block h-1.5 w-full rounded bg-white/25" /><i className="block h-16 rounded bg-primary/70" /></div></div></div></div><div className="mt-3 grid grid-cols-4 gap-2">{["landing", "mobile", "cards", "course"].map((art) => <div key={art} className={`product-art ${art} h-14 rounded border-2 ${art === "landing" ? "border-primary" : "border-transparent"}`} />)}</div></div><div className="mt-5 rounded-xl border border-[#e5ebf4] bg-white p-5 shadow-sm"><h2 className="text-sm font-bold">About This Product</h2><p className="mt-3 text-xs leading-6 text-slate-500">The Startup Landing Page template is a modern, clean and professional landing page design perfect for startups, SaaS, apps, and digital products. It comes with a beautiful UI, responsive layout, and is easy to customize.</p><ul className="mt-4 grid gap-2 text-[10px] text-slate-600 sm:grid-cols-2">{["Modern and clean design", "Fully responsive (mobile, tablet, desktop)", "Easy to edit (no coding required)", "Well organized layers and components", "Free updates & support"].map((item) => <li key={item}><span className="mr-2 text-primary">✓</span>{item}</li>)}</ul><div className="mt-5 rounded-lg bg-orange-50 p-3 text-[10px] text-slate-500">💡　This is a digital product. After purchase, you will get instant access to download the files.</div></div></section>

      <section className="pt-2"><span className="rounded-full bg-indigo-100 px-3 py-1 text-[10px] font-semibold text-indigo-600">{product.type}</span><h1 className="mt-4 text-3xl font-extrabold tracking-tight sm:text-4xl">{product.name}</h1><p className="mt-3 text-sm leading-6 text-slate-500">A modern and responsive landing page template for startups, apps and digital products. Perfect for your next project.</p><p className="mt-5 text-amber-500">★★★★★ <b className="ml-2 text-xs text-slate-700">4.8</b> <span className="text-xs text-slate-500">(124 reviews)　|　245 sold</span></p><div className="mt-5 flex items-center gap-3"><b className="text-4xl">{product.price}</b><del className="text-sm text-slate-400">{product.oldPrice}</del><span className="rounded bg-orange-100 px-3 py-1.5 text-xs font-bold text-primary">38% OFF</span></div><div className="mt-5 flex flex-wrap gap-2">{["HTML", "CSS", "JavaScript", "Responsive", "5 Files Included"].map((tag) => <span key={tag} className="rounded-lg bg-white px-3 py-2 text-[10px] text-slate-500 shadow-sm ring-1 ring-[#e8edf5]">▧　{tag}</span>)}</div><p className="mt-7 text-xs font-bold">Quantity</p><div className="mt-2 flex w-28 overflow-hidden rounded-lg border border-[#dce4f0] bg-white"><button type="button" className="w-9 py-2 text-slate-500">−</button><span className="flex-1 border-x border-[#dce4f0] py-2 text-center text-xs font-bold">1</span><button type="button" className="w-9 py-2 text-slate-500">+</button></div><StorefrontCartButton id="startup-landing-page" name={product.name} type={product.type} price={product.price} href={productPath} /><button type="button" className="mt-3 flex w-full items-center justify-center gap-2 rounded-lg border border-primary px-4 py-3 text-xs font-bold text-primary">⚡　Buy Now</button><div className="mt-5 rounded-xl bg-orange-50 p-4"><p className="text-xs font-semibold text-primary">▣　Instant Download</p><p className="mt-1 text-[10px] text-slate-500">Get your files right after payment.</p></div></section>

      <aside className="space-y-4"><div className="rounded-xl border border-[#e5ebf4] bg-white p-4 shadow-sm"><h2 className="text-sm font-bold">Why Choose Us?</h2>{[["◈", "100% Original Products", "All products are created by real creators."], ["♢", "Secure Payment", "Multiple payment methods supported."], ["⇩", "Instant Download", "Get your files immediately."], ["◌", "24/7 Support", "We're here to help you anytime."]].map(([icon, title, detail]) => <div key={title} className="mt-5 flex gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-orange-50 text-primary">{icon}</span><span><b className="block text-[10px]">{title}</b><small className="mt-1 block text-[9px] leading-4 text-slate-500">{detail}</small></span></div>)}</div><div className="rounded-xl border border-[#e5ebf4] bg-white p-4 shadow-sm"><h2 className="text-sm font-bold">Seller Information</h2><div className="mt-4 flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-full bg-gradient-to-br from-amber-300 to-[#9b5d10] text-xl text-white">N</span><span><b className="block text-xs">{name}</b><small className="text-[10px] text-primary">♛ Top Seller</small></span></div><div className="mt-5 grid grid-cols-3 text-center text-[9px] text-slate-500"><span><b className="block text-xs text-slate-800">245</b>Products</span><span><b className="block text-xs text-slate-800">4.8</b>Rating</span><span><b className="block text-xs text-slate-800">1.2k</b>Followers</span></div><Link href={basePath} className="mt-5 block rounded-lg border border-[#dce4f0] py-2 text-center text-[10px] font-semibold text-primary">View Store　→</Link></div><div className="rounded-xl border border-[#e5ebf4] bg-white p-4 shadow-sm"><h2 className="text-sm font-bold">Share This Product</h2><div className="mt-4 flex gap-2"><span className="grid h-8 w-8 place-items-center rounded-full bg-blue-50 text-xs text-blue-500">f</span><span className="grid h-8 w-8 place-items-center rounded-full bg-blue-50 text-xs text-blue-500">♥</span><span className="grid h-8 w-8 place-items-center rounded-full bg-blue-50 text-xs text-blue-500">in</span><button type="button" className="ml-auto rounded border border-[#dce4f0] px-3 text-[9px] text-slate-500"><PublicIcon name="link" className="mr-1 inline h-3 w-3" />Copy Link</button></div></div></aside>
    </div></div><PublicFooter /></main>;
}
