"use client";

import { useState } from "react";
import PublicIcon from "@/components/icons/PublicIcon";

const content = { purchases: ["Purchases", "Review your marketplace orders and purchase history.", ["#ORD-3658", "#ORD-3657", "#ORD-3656"]], downloads: ["Downloads", "Access your purchased files and download history.", ["Premium Template Pack", "UI Design Kit", "Icon Set Collection"]], licenses: ["Licenses", "Manage your active product licenses and keys.", ["Premium Template Pack", "Laravel API Mastery", "WordPress Plugin"]], reviews: ["My Reviews", "Share feedback on the products you have purchased.", ["Premium Template Pack", "UI Design Kit", "Icon Set Collection"]], account: ["Account Settings", "Manage your buyer profile and preferences.", ["Profile information", "Security and password", "Notification preferences"]] } as const;
type BuyerView = keyof typeof content;

export default function BuyerSection({ view }: { view: BuyerView }) {
  const [notice, setNotice] = useState(false);
  const [heading, description, records] = content[view];
  return <div className="mx-auto w-full max-w-[1400px]"><header className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-2xl font-bold tracking-tight text-heading sm:text-[28px]">{heading}</h1><p className="mt-1 text-sm text-muted">{description}</p></div><button type="button" onClick={() => setNotice(true)} className="inline-flex items-center justify-center gap-2 rounded-lg bg-primary px-3.5 py-2 text-xs font-semibold text-white hover:bg-primary-hover"><PublicIcon name={view === "account" ? "edit" : "download"} className="h-3.5 w-3.5" />{view === "account" ? "Edit profile" : "Export"}</button></header>{notice && <p className="mt-4 rounded-lg bg-emerald-50 px-3 py-2 text-xs text-status-success">Action completed successfully.</p>}<section className="mt-6 overflow-hidden rounded-2xl border border-border bg-white shadow-sm"><div className="border-b border-divider px-5 py-4"><h2 className="text-sm font-bold text-heading">{heading}</h2></div><div className="divide-y divide-divider">{records.map((record, index) => <article key={record} className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-orange-50 text-primary"><PublicIcon name={view === "licenses" ? "key" : view === "downloads" ? "download" : view === "account" ? "user" : view === "reviews" ? "verified" : "receipt"} className="h-4 w-4" /></span><div><p className="text-xs font-semibold text-body">{record}</p><p className="mt-1 text-[10px] text-muted">{view === "account" ? "Update your account details" : index === 0 ? "Updated recently" : "May {22 - index}, 2025"}</p></div></div><span className={`w-fit rounded-full px-2.5 py-1 text-[9px] font-semibold ${view === "licenses" ? "bg-emerald-50 text-status-success" : "bg-surface-muted text-muted"}`}>{view === "licenses" ? "Active" : view === "account" ? "Manage" : "View details"}</span></article>)}</div></section></div>;
}