"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import AppBrand from "@/components/AppBrand";
import PublicIcon from "@/components/icons/PublicIcon";

const sections = [
  { title: "Content Review", items: [["Pending Products", "product", "/reviewer/pending-products"], ["Product Review", "file-search-corner", "/reviewer/product-review"], ["File Review", "file-search-corner", "/reviewer/file-review"], ["Preview Assets", "view", "/reviewer/preview-assets"]] },
  { title: "Moderation", items: [["Flagged Content", "warning", "/reviewer/flagged-content"], ["Content Reports", "receipt", "/reviewer/content-reports"], ["Content Violations", "shield-minus", "/reviewer/content-violations"]] },
  { title: "Reviews", items: [["Customer Reviews", "message-square-reply", "/reviewer/customer-reviews"], ["Reported Reviews", "warning", "/reviewer/reported-reviews"], ["Review Moderation", "shield-check", "/reviewer/review-moderation"]] },
  { title: "DMCA", items: [["DMCA Activity", "shield-check", "/reviewer/dmca"], ["Takedown Requests", "x", "/reviewer/takedown-requests"], ["Counter-Notices", "message-square-reply", "/reviewer/counter-notices"], ["Restored Content", "rotate-ccw", "/reviewer/restored-content"]] },
] as const;

export default function ReviewerDashboardSidebar({ open, collapsed, onClose, onToggle }: { open: boolean; collapsed: boolean; onClose: () => void; onToggle: () => void }) {
  const pathname = usePathname();
  return <><button type="button" aria-label="Close dashboard navigation" onClick={onClose} className={`fixed inset-0 z-[70] bg-slate-950/45 backdrop-blur-[1px] transition-opacity duration-300 min-[901px]:hidden ${open ? "pointer-events-auto opacity-100" : "pointer-events-none opacity-0"}`} /><button type="button" onClick={onToggle} aria-label={collapsed ? "Expand sidebar" : "Collapse sidebar"} className={`fixed top-20 z-[60] grid h-9 w-9 place-items-center rounded-br-lg border-b border-r border-[#e1e5ee] bg-white text-xl shadow-md transition-[left] duration-300 hover:bg-accent-light max-[900px]:hidden ${collapsed ? "left-0" : "left-[228px]"}`}>{collapsed ? "›" : "‹"}</button><aside className={`scrollbar-hidden fixed inset-y-0 left-0 z-[80] flex w-[70%] max-w-[28rem] flex-col overflow-y-auto border-r border-[#eaebf5] bg-white px-5 py-5 shadow-xl transition-[width,transform,padding] duration-300 min-[901px]:sticky min-[901px]:top-20 min-[901px]:h-[calc(100vh-5rem)] min-[901px]:translate-x-0 min-[901px]:shadow-none ${open ? "translate-x-0" : "-translate-x-full"} ${collapsed ? "min-[901px]:w-0 min-[901px]:overflow-hidden min-[901px]:border-r-0 min-[901px]:px-0" : "min-[901px]:w-[264px]"}`}><button type="button" onClick={onClose} className="mb-4 self-end text-lg min-[901px]:hidden" aria-label="Close dashboard navigation">×</button><Link href="/" onClick={onClose} className="mb-5 flex items-center no-underline min-[901px]:hidden"><AppBrand className="min-w-0" textClassName="text-lg" logoClassName="h-9 w-9" /></Link><div className="mb-6 flex items-center gap-3 rounded-lg border border-[#e9edf6] bg-[#f4f7ff] px-3 py-3 text-primary"><span className="grid h-9 w-9 place-items-center rounded-lg bg-accent-light"><PublicIcon name="shield-check" /></span><span><span className="block text-[13px] font-semibold">Reviewer workspace</span><span className="block text-[11px] text-gray-500">Content safety</span></span></div><Link href="/reviewer" onClick={onClose} className={`mb-5 flex items-center gap-4 rounded-lg px-4 py-3 text-sm no-underline ${pathname === "/reviewer" ? "bg-accent-light font-medium text-primary" : "text-[#1d294b] hover:bg-slate-50"}`}><PublicIcon name="dashboard" />Dashboard</Link>{sections.map((section) => <section key={section.title} className="mt-5"><h2 className="mb-1 px-4 text-[9px] font-semibold uppercase tracking-[0.08em] text-[#8993aa]">{section.title}</h2><div className="space-y-1">{section.items.map(([label, icon, href]) => <Link key={label} href={href} onClick={onClose} className={`flex items-center gap-4 rounded-lg px-4 py-3 text-sm no-underline ${pathname === href || pathname.startsWith(`${href}/`) ? "bg-accent-light font-medium text-primary" : "text-[#1d294b] hover:bg-slate-50"}`}><PublicIcon name={icon} />{label}</Link>)}</div></section>)}</aside></>;
}