"use client";

import { useState } from "react";
import Link from "next/link";
import { Toast } from "@/components/ui";

export default function CreateAffiliateLinkPage() {
  const [saved, setSaved] = useState(false);
  return <div className="mx-auto w-full max-w-[900px]">{saved && <Toast variant="success" message="Affiliate link created successfully." onClose={() => setSaved(false)} />}<header><h1 className="text-2xl font-bold tracking-tight text-heading sm:text-[28px]">Create Affiliate Link</h1><p className="mt-1 text-sm text-muted">Create a trackable link for a product you want to promote.</p></header><form onSubmit={(event) => { event.preventDefault(); setSaved(true); }} className="mt-6 rounded-2xl border border-border bg-white p-5 shadow-sm sm:p-6"><div className="grid gap-5 sm:grid-cols-2"><label className="text-xs font-semibold text-body">Product<select required defaultValue="" className="select-chevron mt-1.5 h-10 w-full rounded-lg border border-border-control bg-white px-3 pr-9 text-xs text-body outline-none focus:border-primary"><option value="" disabled>Select product</option><option>Premium Template Pack</option><option>UI Design Kit</option><option>Icon Set Collection</option></select></label><label className="text-xs font-semibold text-body">Campaign name<input required placeholder="Summer promotion" className="mt-1.5 h-10 w-full rounded-lg border border-border-control px-3 text-xs text-body outline-none placeholder:text-muted-faint focus:border-primary" /></label></div><label className="mt-5 block text-xs font-semibold text-body">Custom tracking note<textarea rows={4} placeholder="Optional note for this campaign" className="mt-1.5 w-full resize-y rounded-lg border border-border-control px-3 py-2.5 text-xs text-body outline-none placeholder:text-muted-faint focus:border-primary" /></label><div className="mt-6 flex justify-end gap-2 border-t border-divider pt-5"><Link href="/creator/affiliate/links" className="rounded-lg border border-border-control px-4 py-2 text-xs font-medium text-muted no-underline hover:bg-surface-control">Cancel</Link><button type="submit" className="rounded-lg bg-primary px-4 py-2 text-xs font-semibold text-white hover:bg-primary-hover">Create Link</button></div></form></div>;
}
