"use client";

import PublicIcon from "@/components/icons/PublicIcon";
import { Badge, Button, InputText, Table, TableHeader, TableRow } from "@/components/ui";

type PayoutStatus = "Completed" | "Processing";
type Payout = { id: string; amount: string; method: string; status: PayoutStatus; date: string };

const payouts: Payout[] = [
  { id: "#PAY-0018", amount: "$620.00", method: "Bank Transfer", status: "Processing", date: "May 16, 2024" },
  { id: "#PAY-0017", amount: "$940.00", method: "PayPal", status: "Completed", date: "Apr 22, 2024" },
  { id: "#PAY-0016", amount: "$550.00", method: "Bank Transfer", status: "Completed", date: "Apr 08, 2024" },
  { id: "#PAY-0015", amount: "$620.00", method: "PayPal", status: "Completed", date: "Mar 25, 2024" },
  { id: "#PAY-0014", amount: "$468.70", method: "Bank Transfer", status: "Completed", date: "Mar 15, 2024" },
  { id: "#PAY-0013", amount: "$512.30", method: "Bank Transfer", status: "Completed", date: "Mar 10, 2024" },
];

const statusTone = { Completed: "success", Processing: "warning" } as const;

function SummaryCard({ label, value, detail, icon, tone }: { label: string; value: string; detail: string; icon: string; tone: string }) {
  return <article className="rounded-xl border border-border bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] text-muted-soft">{label}</p><p className="mt-2 text-lg font-bold text-ink">{value}</p></div><span className={`grid h-9 w-9 place-items-center rounded-lg ${tone}`}><PublicIcon name={icon as any} className="h-5 w-5" /></span></div><p className="mt-2 text-[9px] text-muted-soft">{detail}</p></article>;
}

export default function CreatorPayoutsPage() {
  return (
    <div className="mx-auto w-full max-w-[1400px]">
      <header className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-2xl font-bold tracking-tight text-heading sm:text-[28px]">Payouts</h1><p className="mt-1 text-sm text-muted">Track your earnings and payout history.</p></div><div className="flex items-center gap-2"><Button size="sm" variant="secondary"><PublicIcon name="settings" className="h-3.5 w-3.5" />Payout Settings</Button><Button size="sm" variant="secondary"><PublicIcon name="down" className="h-3.5 w-3.5 rotate-180" />Export</Button></div></header>
      <section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><SummaryCard label="Available Balance" value="$1,240.50" detail="↑ 12.4% vs. last month" icon="dollar" tone="bg-emerald-50 text-status-success" /><SummaryCard label="Pending Payout" value="$620.00" detail="Next payout in 3 days" icon="notification" tone="bg-orange-50 text-primary" /><SummaryCard label="Total Paid" value="$5,280.75" detail="Across 18 payouts" icon="verified" tone="bg-blue-50 text-status-info" /><SummaryCard label="Payout Methods" value="2" detail="Active methods" icon="payment" tone="bg-purple-50 text-purple-600" /></section>
      <div className="mt-5 grid gap-5 xl:grid-cols-[1.4fr_0.6fr]">
        <section className="overflow-hidden rounded-2xl border border-border bg-white shadow-sm"><div className="border-b border-divider px-5 py-4 sm:px-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><h2 className="text-sm font-bold text-heading">Payout History</h2><div className="flex gap-2"><label className="relative"><span className="sr-only">Search payouts</span><PublicIcon name="search" className="absolute left-3 top-2.5 h-4 w-4 text-muted-faint" /><InputText placeholder="Search payouts..." className="h-9 w-full pl-9 text-xs sm:w-56" /></label><select className="h-9 rounded-lg border border-border-control bg-white px-3 text-xs text-body outline-none focus:border-primary" aria-label="Payout status filter"><option>All Status</option><option>Completed</option><option>Processing</option></select></div></div></div><Table className="min-w-[680px]"><TableHeader><tr><th className="px-6 py-3 font-medium">Payout ID</th><th className="py-3 font-medium">Amount</th><th className="py-3 font-medium">Method</th><th className="py-3 font-medium">Status</th><th className="py-3 font-medium">Date</th><th className="px-6 py-3 text-right font-medium">Actions</th></tr></TableHeader><tbody>{payouts.map((payout) => <TableRow key={payout.id} className="text-body transition hover:bg-surface-hover"><td className="px-6 py-3 text-[10px] font-medium text-body-strong">{payout.id}</td><td className="py-3 font-semibold text-body-strong">{payout.amount}</td><td className="py-3 text-[10px] text-muted">{payout.method}</td><td className="py-3"><Badge tone={statusTone[payout.status]}>{payout.status}</Badge></td><td className="py-3 text-[10px] text-muted">{payout.date}</td><td className="px-6 py-3 text-right"><button type="button" aria-label={`View ${payout.id}`} className="inline-grid h-7 w-7 place-items-center rounded-md border border-border-action text-muted hover:border-primary hover:text-primary"><PublicIcon name="view" className="h-3.5 w-3.5" /></button></td></TableRow>)}</tbody></Table><footer className="flex items-center justify-between border-t border-divider px-6 py-4 text-[10px] text-muted"><span>Showing 6 of 25 payouts</span><span>View All Payouts <PublicIcon name="right" className="ml-1 inline h-3 w-3" /></span></footer></section>
        <div className="space-y-5"><section className="rounded-2xl border border-border bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h2 className="text-sm font-bold text-heading">Next Payout</h2><p className="mt-1 text-[10px] text-muted-soft">Scheduled for May 19, 2024</p></div><Badge tone="warning">Processing</Badge></div><p className="mt-5 text-2xl font-bold text-ink">$620.00</p><div className="mt-5 flex items-end justify-between border-t border-divider pt-4 text-[9px] text-muted-soft"><span>May 13</span><span>May 19</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-surface-muted"><div className="h-full w-[72%] rounded-full bg-primary" /></div><div className="mt-2 flex justify-between text-[9px] text-muted"><span>Processing</span><span>Transfer</span><span>Paid</span></div></section><section className="rounded-2xl border border-border bg-white p-5 shadow-sm"><h2 className="text-sm font-bold text-heading">Payout Methods</h2><div className="mt-4 space-y-3"><div className="flex items-center justify-between border-b border-divider pb-3"><div className="flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-md bg-blue-50 text-status-info"><PublicIcon name="bank" className="h-3.5 w-3.5" /></span><div><p className="text-[10px] font-semibold text-body-strong">ABA Bank</p><p className="text-[9px] text-muted-soft">**** 1234</p></div></div><Badge tone="success">Primary</Badge></div><div className="flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-md bg-blue-50 text-status-info"><PublicIcon name="payment" className="h-3.5 w-3.5" /></span><div><p className="text-[10px] font-semibold text-body-strong">PayPal</p><p className="text-[9px] text-muted-soft">nourchomrong@gmail.com</p></div></div></div><Button size="sm" variant="secondary" className="mt-4 w-full">Manage Methods</Button></section></div>
      </div>
    </div>
  );
}
