"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import PublicIcon from "@/components/icons/PublicIcon";

const sections = [
  { title: "User & Access", items: [["Users", "user", "/admin/users"], ["Roles & Permissions", "shield-check", "/admin/roles"], ["Content Rights", "key", "/admin/content-rights"]] },
  { title: "Activity & Security", items: [["Activity Log", "file-search-corner", "/admin/activity"], ["Download Events", "download", "/admin/downloads"], ["License Activations", "verification", "/admin/license-activations"], ["Refund Requests", "rotate-ccw", "/admin/refunds"], ["DMCA Activity", "shield-minus", "/admin/dmca"]] },
  { title: "Creators & Storefronts", items: [["Creators", "store", "/admin/creators"], ["Storefronts", "store", "/admin/storefronts"], ["Verification Requests", "verification", "/admin/verification"], ["Payout Information", "payout", "/admin/payouts"], ["Reviewers", "user", "/admin/reviewers"], ["Affiliate Program", "up", "/admin/affiliate-program"]] },
  { title: "Products & Files", items: [["Products", "product", "/admin/products"], ["Files", "file-search-corner", "/admin/files"], ["Version History", "rotate-ccw", "/admin/versions"], ["Preview Assets", "view", "/admin/preview-assets"]] },
  { title: "Licenses & DRM", items: [["License Types", "type", "/admin/license-types"], ["License Keys", "key", "/admin/license-keys"], ["License Activations", "verification", "/admin/activations"], ["Revoked Licenses", "shield-minus", "/admin/revoked-licenses"]] },
  { title: "Orders & Reports", items: [["Orders", "receipt", "/admin/orders"], ["Download Links", "link", "/admin/download-links"], ["Analytics", "dashboard", "/admin/analytics"]] },
] as const;

export default function AdminDashboardSidebar({ open, collapsed, onClose, onToggle }: { open: boolean; collapsed: boolean; onClose: () => void; onToggle: () => void }) {
  const pathname = usePathname();
  const basePath = "/admin";
  return <><button type="button" aria-label="Close dashboard navigation" onClick={onClose} className={`fixed inset-x-0 bottom-0 top-20 z-30 bg-slate-950/30 lg:hidden ${open ? "block" : "hidden"}`} /><button type="button" onClick={onToggle} aria-label={collapsed ? "Expand sidebar" : "Collapse sidebar"} className={`fixed top-20 z-[60] hidden h-9 w-9 place-items-center rounded-br-lg border-b border-r border-[#e1e5ee] bg-white text-xl shadow-md transition-[left] duration-300 hover:bg-accent-light lg:grid ${collapsed ? "left-0" : "left-[228px]"}`}>{collapsed ? "›" : "‹"}</button><aside className={`scrollbar-hidden fixed bottom-0 left-0 top-20 z-40 flex w-[85%] flex-col overflow-y-auto border-r border-[#eaebf5] bg-white px-5 py-5 shadow-xl transition-[width,transform,padding] duration-300 lg:sticky lg:top-20 lg:h-[calc(100vh-5rem)] lg:translate-x-0 lg:shadow-none ${open ? "translate-x-0" : "-translate-x-full"} ${collapsed ? "lg:w-0 lg:overflow-hidden lg:border-r-0 lg:px-0" : "lg:w-[264px]"}`}><button type="button" onClick={onClose} className="mb-4 self-end text-lg lg:hidden" aria-label="Close dashboard navigation">×</button><div className="mb-6 flex items-center gap-3 rounded-lg border border-[#e9edf6] bg-[#f4f7ff] px-3 py-3 text-primary"><span className="grid h-9 w-9 place-items-center rounded-lg bg-accent-light"><PublicIcon name="shield-check" /></span><span><span className="block text-[13px] font-semibold">Admin workspace</span><span className="block text-[11px] text-gray-500">Marketplace control</span></span></div><Link href={basePath} onClick={onClose} className={`mb-5 flex items-center gap-4 rounded-lg px-4 py-3 text-sm no-underline ${pathname === basePath ? "bg-accent-light font-medium text-primary" : "text-[#1d294b] hover:bg-slate-50"}`}><PublicIcon name="dashboard" />Dashboard</Link>{sections.map((section) => <section key={section.title} className="mt-5"><h2 className="mb-1 px-4 text-[9px] font-semibold uppercase tracking-[0.08em] text-[#8993aa]">{section.title}</h2><div className="space-y-1">{section.items.map(([label, icon, href]) => { const itemHref = href.replace("/admin", basePath); return <Link key={label} href={itemHref} onClick={onClose} className={`flex items-center gap-4 rounded-lg px-4 py-3 text-sm no-underline ${pathname === itemHref || pathname.startsWith(`${itemHref}/`) ? "bg-accent-light font-medium text-primary" : "text-[#1d294b] hover:bg-slate-50"}`}><PublicIcon name={icon} />{label}</Link>; })}</div></section>)}</aside></>;
}