import Link from "next/link";

const menus = { admin: ["Users", "Roles", "Permissions", "Activity Logs", "Creators", "Products", "Licenses", "Orders", "Reviews", "DMCA", "Affiliates", "Coupons", "Bundles", "Analytics"], creator: ["Overview", "Store", "Products", "Orders", "Reviews", "Affiliates", "Earnings", "Payouts", "Analytics"], buyer: ["Overview", "Purchases", "Downloads", "Licenses", "Reviews", "Account"] } as const;
type Role = keyof typeof menus;

export default function RoleSection({ role, section }: { role: Role; section?: string }) {
  const heading = section ? section.replaceAll("/", " / ").split(" ").map((word) => word ? word[0].toUpperCase() + word.slice(1) : word).join(" ") : `${role[0].toUpperCase() + role.slice(1)} Dashboard`;
  return <main className="min-h-screen bg-background p-5 text-[#111b40] sm:p-8"><section className="mx-auto max-w-6xl"><Link href="/dashboard" className="text-sm font-medium text-primary no-underline">← All dashboards</Link><div className="mt-4 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold">{heading}</h1><p className="mt-2 text-sm text-[#66718e]">{role[0].toUpperCase() + role.slice(1)} workspace</p></div><Link href={`/dashboard/${role}`} className="rounded-lg border border-[#e0e3ed] bg-white px-4 py-2 text-sm no-underline text-[#27365d]">{role[0].toUpperCase() + role.slice(1)} home</Link></div><div className="mt-8 grid gap-5 lg:grid-cols-[220px_1fr]"><aside className="rounded-xl border border-[#e7e9f2] bg-white p-3">{menus[role].map((item) => <Link key={item} href={`/dashboard/${role}/${item.toLowerCase().replaceAll(" ", "-")}`} className="block rounded-lg px-3 py-2.5 text-sm text-[#35415f] no-underline hover:bg-accent-light">{item}</Link>)}</aside><article className="rounded-xl border border-[#e7e9f2] bg-white p-6 shadow-sm"><span className="grid h-12 w-12 place-items-center rounded-xl bg-accent-light text-xl text-primary">{role === "admin" ? "⌘" : role === "creator" ? "✦" : "◈"}</span><h2 className="mt-5 text-xl font-bold">{heading}</h2><p className="mt-3 text-sm leading-6 text-[#66718e]">This section belongs to the {role} dashboard and is ready for its connected data and workflows.</p></article></div></section></main>;
}
