"use client";

import { useState } from "react";
import PublicIcon, { type PublicIconName, type PublicIconSidebarName } from "@/components/icons/PublicIcon";
import ProductPagination from "@/components/products/ProductPagination";
import { Badge } from "@/components/ui";

export type AdminSection = string;
type Column = string;
type PageConfig = { title: string; description: string; columns: Column[]; metrics: [string, string, string, PublicIconName | PublicIconSidebarName][]; rows: string[][]; filters: string[] };

const people = ["Jane Cooper", "Brooklyn Simmons", "Cody Fisher", "Dianne Russell", "Devon Lane"];
const products = ["Premium UI Kit", "Music Pack Vol 1", "3D Icon Set", "Video LUTs Pack", "E-book Design Guide"];
const dates = ["May 11, 2025", "May 10, 2025", "May 9, 2025", "May 8, 2025", "May 7, 2025"];
const withActions = (rows: string[][]) => rows.map((row) => [...row, "Actions"]);
const email = (name: string) => `${name.toLowerCase().replace(" ", ".")}@example.com`;

const pages: Partial<Record<AdminSection, PageConfig>> = {
  users: { title: "Users", description: "Manage marketplace users, roles, and account status.", metrics: [["Total Users", "12,458", "+12.3%", "user"], ["Active Users", "9,842", "+10.1%", "user"], ["Suspended Users", "320", "-2.1%", "shield-minus"], ["New This Month", "1,245", "+6.5%", "user"]], columns: ["User", "Email", "Role", "Status", "Joined Date", "Actions"], filters: ["All Roles", "All Status"], rows: withActions(people.map((name, index) => [name, email(name), index % 2 ? "Customer" : "Creator", index === 3 ? "Suspended" : "Active", dates[index]])) },
  roles: { title: "Roles & Permissions", description: "Control access to marketplace features and settings.", metrics: [], columns: ["Role Name", "Description", "Users", "Last Updated", "Actions"], filters: [], rows: withActions([["Super Admin", "Full access to all features and settings", "2", dates[0]], ["Admin", "Manage system settings and users", "5", dates[1]], ["Creator", "Can manage own products and sales", "1,245", dates[2]], ["Moderator", "Can moderate content and users", "12", dates[3]], ["Customer", "Can browse and purchase products", "9,158", dates[4]]]) },
  "content-rights": { title: "Content Rights", description: "Review ownership and usage rights across marketplace content.", metrics: [["Total Rights", "3,245", "+12.4%", "key"], ["Active Rights", "2,890", "+11.1%", "verification"], ["Expired", "210", "+2.5%", "clock-9"], ["Revoked", "145", "-3.1%", "shield-minus"]], columns: ["Content Name", "Type", "Usage Method", "Status", "Valid Until", "Actions"], filters: ["All Types", "All Status"], rows: withActions(products.map((product, index) => [product, ["Template", "Audio", "Graphics", "Video", "E-book"][index], ["UI Master", "Sound Source", "Design Hub", "Visual Flow", "Creative Writer"][index], index === 2 ? "Expired" : "Active", "May 11, 2026"])) },
  activity: { title: "Activity Log", description: "Monitor account and marketplace activity across the platform.", metrics: [], columns: ["Time", "User", "Action", "Details", "IP Address"], filters: ["All Actions", "All Users"], rows: [["May 11, 2025 04:45 PM", "Admin", "Login", "Admin logged in", "192.168.1.10"], ["May 11, 2025 02:02 PM", people[0], "Updated Product", "Updated product Music UI Kit", "192.168.1.21"], ["May 11, 2025 01:15 PM", people[1], "Deleted Content", "Deleted Template", "192.168.1.15"], ["May 11, 2025 08:20 AM", people[2], "Suspended User", "Suspended user account", "192.168.1.30"], ["May 10, 2025 06:20 PM", "Admin", "Changed Settings", "Updated payout settings", "192.168.1.10"]] },
  downloads: { title: "Download Events", description: "Review product download activity and access locations.", metrics: [], columns: ["Time", "User", "Product", "Version", "IP Address", "Location"], filters: ["All Products", "All Dates"], rows: products.map((product, index) => [dates[index], people[index], product, `v${index + 1}.0`, `192.168.1.${10 + index}`, ["London, UK", "Toronto, Canada", "Sydney, Australia", "Berlin, Germany", "Tokyo, Japan"][index]]) },
  "license-activations": { title: "License Activations", description: "Track activated licenses and the devices using them.", metrics: [], columns: ["Time", "User", "Product", "License Key", "Status", "Device"], filters: ["All Products", "All Status"], rows: products.map((product, index) => [dates[index], people[index], product, `XXXX-XXXX-XXXX-${1234 + index}`, index === 2 ? "Revoked" : "Active", ["Windows 11", "Windows 10", "MacOS 14", "Android 14", "iOS 18"][index]]) },
  refunds: { title: "Refund Requests", description: "Review and process customer refund requests.", metrics: [["Total Requests", "245", "+10.2%", "receipt"], ["Pending", "32", "+3.1%", "clock-9"], ["Approved", "182", "+12.1%", "check"], ["Rejected", "31", "-4.3%", "x"]], columns: ["Request ID", "User", "Product", "Amount", "Status", "Requested At", "Actions"], filters: ["All Status"], rows: withActions(products.map((product, index) => [`RFR-00024${5 - index}`, people[index], product, `$${19 + index * 10}.00`, index === 2 ? "Rejected" : index % 2 ? "Approved" : "Pending", dates[index]])) },
  dmca: { title: "DMCA Activity", description: "Track copyright notices, reports, and takedown activity.", metrics: [["Total Reports", "78", "+5.8%", "file-search-corner"], ["Pending", "12", "+1.2%", "clock-9"], ["Resolved", "56", "+8.3%", "check"], ["Rejected", "10", "-4.6%", "x"]], columns: ["Report ID", "Reported By", "Content", "Status", "Reported At", "Actions"], filters: ["All Status"], rows: withActions(products.map((product, index) => [`DMCA-007${8 - index}`, people[index], `Pirated ${product}`, index === 4 ? "Rejected" : index % 2 ? "Resolved" : "Pending", dates[index]])) },
  creators: { title: "Creators", description: "Manage creators on the marketplace.", metrics: [["Total Creators", "386", "+12.4%", "store"], ["Active Creators", "324", "+7.1%", "store"], ["Verified Creators", "278", "+15.3%", "verified"], ["Suspended", "12", "-2.1%", "shield-minus"]], columns: ["Creator", "Email", "Storefronts", "Status", "Verification", "Joined", "Actions"], filters: ["All Status", "All Verification"], rows: withActions(people.map((name, index) => [name, email(name), `${index + 1}`, index === 4 ? "Suspended" : "Active", index === 2 ? "Pending" : index === 4 ? "Rejected" : "Verified", dates[index]])) },
  "affiliate-program": { title: "Affiliate Program", description: "Manage affiliates and their performance.", metrics: [["Total Affiliates", "542", "+8.6%", "user"], ["Active Affiliates", "438", "+14.2%", "user"], ["Total Commissions", "$12,450.75", "+22.3%", "dollar"], ["Pending Payouts", "$2,340.50", "+5.8%", "wallet"]], columns: ["Affiliate", "Email", "Tier", "Referrals", "Earnings", "Status", "Actions"], filters: ["All Status", "All Tiers"], rows: withActions(people.map((name, index) => [name, email(name), ["Gold", "Silver", "Bronze", "Silver", "Bronze"][index], `${92 - index * 12}`, `$${2450 - index * 400}.75`, index === 3 ? "Inactive" : "Active"])) },
  reviewers: { title: "Reviewers", description: "Manage product reviewers and their activity.", metrics: [["Total Reviewers", "128", "+2.1%", "user"], ["Active Reviewers", "102", "+7.1%", "user"], ["Total Reviews", "1,245", "+13.6%", "message-square-reply"], ["Pending Reviews", "23", "+4.7%", "clock-9"]], columns: ["Reviewer", "Email", "Expertise", "Reviews", "Rating", "Status", "Actions"], filters: ["All Status", "All Expertise"], rows: withActions(people.map((name, index) => [name, email(name), ["UI/UX, Templates", "Graphics, Icons", "Audio, Music", "3D, Models", "Code, Software"][index], `${56 - index * 7}`, `4.${8 - index % 3}`, index === 3 ? "Inactive" : "Active"])) },
  storefronts: { title: "Storefronts", description: "Manage creator storefronts.", metrics: [["Total Storefronts", "812", "+15.2%", "store"], ["Active Storefronts", "742", "+11.8%", "store"], ["Inactive Storefronts", "58", "-3.4%", "store"], ["Suspended", "12", "-2.1%", "shield-minus"]], columns: ["Storefront", "Creator", "Category", "Products", "Status", "Created", "Actions"], filters: ["All Status", "All Categories"], rows: withActions(["DesignHub", "CodeCraft", "AudioWave", "PixelPerfect", "3DAssets"].map((storefront, index) => [storefront, people[index], ["Templates", "Code", "Audio", "Graphics", "3D Models"][index], `${124 - index * 15}`, index === 4 ? "Suspended" : "Active", dates[index]])) },
  verification: { title: "Verification Requests", description: "Review and manage creator verification requests.", metrics: [["Total Requests", "245", "+10.2%", "verification"], ["Pending", "32", "+5.4%", "clock-9"], ["Approved", "182", "+12.1%", "check"], ["Rejected", "31", "-3.2%", "x"]], columns: ["Creator", "Email", "Requested On", "Documents", "Status", "Actions"], filters: ["All Status"], rows: withActions(people.map((name, index) => [name, email(name), dates[index], `${index + 2} files`, index === 3 ? "Rejected" : index < 2 ? "Pending" : "Approved"])) },
  payouts: { title: "Payout Information", description: "Manage creator payout settings and methods.", metrics: [["Total Payouts", "$125,430.50", "+16.8%", "payout"], ["Pending Payouts", "$12,340.75", "+3.2%", "clock-9"], ["Available Balance", "$8,950.20", "+9.3%", "wallet"], ["This Month", "$15,230.40", "+12.4%", "dollar"]], columns: ["Creator", "Payment Method", "Account / Email", "Available Balance", "Status", "Actions"], filters: ["All Status", "All Methods"], rows: withActions(people.map((name, index) => [name, ["PayPal", "Bank Transfer", "Payoneer", "Wise", "Bank Transfer"][index], email(name), `$${1240 - index * 180}.50`, index === 3 ? "Pending" : "Active"])) },
  products: { title: "Products", description: "Manage marketplace products, publishing status, and ownership.", metrics: [["Total Products", "2,845", "+6.3%", "product"], ["Published", "2,410", "+8.1%", "check"], ["Drafts", "286", "+4.2%", "file"], ["Under Review", "149", "+2.8%", "clock-9"]], columns: ["Product", "Creator", "Category", "Price", "Status", "Updated", "Actions"], filters: ["All Status", "All Categories"], rows: withActions(products.map((product, index) => [product, people[index], ["Templates", "Audio", "Graphics", "Video", "E-books"][index], `$${19 + index * 10}.00`, index === 2 ? "Draft" : index === 3 ? "Pending" : "Published", dates[index]])) },
  files: { title: "Files", description: "Review uploaded product files, storage, and processing status.", metrics: [["Total Files", "8,426", "+9.4%", "file-search-corner"], ["Storage Used", "184.6 GB", "+12.1%", "database"], ["Processed", "8,102", "+8.8%", "check"], ["Needs Review", "324", "+3.6%", "clock-9"]], columns: ["File Name", "Product", "Type", "Size", "Status", "Uploaded", "Actions"], filters: ["All Status", "All Types"], rows: withActions([["ui-kit-source.zip", products[0], "ZIP", "248 MB", "Ready", dates[0]], ["music-pack-vol-1.wav", products[1], "Audio", "1.4 GB", "Ready", dates[1]], ["icon-set-assets.rar", products[2], "Archive", "620 MB", "Review", dates[2]], ["lut-preview-pack.zip", products[3], "ZIP", "392 MB", "Ready", dates[3]], ["ebook-source.pdf", products[4], "PDF", "84 MB", "Processing", dates[4]]]) },
  versions: { title: "Version History", description: "Track product releases and version changes across the marketplace.", metrics: [["Total Versions", "6,284", "+11.4%", "rotate-ccw"], ["Released", "5,912", "+10.6%", "check"], ["In Review", "246", "+4.8%", "clock-9"], ["Archived", "126", "-2.1%", "archive"]], columns: ["Version", "Product", "Creator", "Release Notes", "Status", "Released", "Actions"], filters: ["All Status", "All Products"], rows: withActions([["v2.4.0", products[0], people[0], "Added component library", "Published", dates[0]], ["v1.8.2", products[1], people[1], "New loop collection", "Published", dates[1]], ["v3.1.0", products[2], people[2], "Updated SVG exports", "In Review", dates[2]], ["v2.0.1", products[3], people[3], "Improved color profiles", "Published", dates[3]], ["v1.2.0", products[4], people[4], "Accessibility fixes", "Archived", dates[4]]]) },
  "preview-assets": { title: "Preview Assets", description: "Manage screenshots, demos, and preview media for marketplace products.", metrics: [["Total Assets", "4,215", "+7.5%", "view"], ["Approved", "3,864", "+9.1%", "check"], ["Pending Review", "286", "+4.4%", "clock-9"], ["Rejected", "65", "-1.8%", "x"]], columns: ["Asset", "Product", "Type", "Uploaded By", "Status", "Updated", "Actions"], filters: ["All Status", "All Types"], rows: withActions([["ui-kit-gallery-01.png", products[0], "Screenshot", people[0], "Approved", dates[0]], ["music-pack-demo.mp3", products[1], "Audio Demo", people[1], "Approved", dates[1]], ["icon-set-preview.png", products[2], "Screenshot", people[2], "Pending", dates[2]], ["lut-before-after.jpg", products[3], "Image", people[3], "Approved", dates[3]], ["ebook-cover.jpg", products[4], "Cover", people[4], "Rejected", dates[4]]]) },
  "license-types": { title: "License Types", description: "Configure the license options available for marketplace products.", metrics: [["License Types", "12", "+2", "type"], ["Active Types", "9", "+1", "check"], ["Products Using Licenses", "2,640", "+8.2%", "product"], ["Archived Types", "3", "-1", "archive"]], columns: ["License Type", "Description", "Products", "Default Term", "Status", "Updated", "Actions"], filters: ["All Status"], rows: withActions([["Standard License", "Personal and commercial use", "1,842", "Lifetime", "Active", dates[0]], ["Extended License", "Expanded redistribution rights", "624", "Lifetime", "Active", dates[1]], ["Team License", "Use across one organization", "174", "1 year", "Active", dates[2]], ["Editorial License", "Editorial and educational use", "96", "Lifetime", "Active", dates[3]], ["Legacy License", "Previous marketplace terms", "0", "Lifetime", "Archived", dates[4]]]) },
  "license-keys": { title: "License Keys", description: "Manage issued keys and monitor license key status.", metrics: [["Issued Keys", "24,580", "+12.7%", "key"], ["Active Keys", "21,436", "+10.2%", "check"], ["Expired Keys", "2,814", "+3.1%", "clock-9"], ["Revoked Keys", "330", "-1.4%", "shield-minus"]], columns: ["License Key", "User", "Product", "License Type", "Status", "Issued", "Actions"], filters: ["All Status", "All Products"], rows: withActions([["XXXX-4821-9A2F", people[0], products[0], "Standard", "Active", dates[0]], ["XXXX-7310-B4C8", people[1], products[1], "Extended", "Active", dates[1]], ["XXXX-1964-D7E1", people[2], products[2], "Team", "Expired", dates[2]], ["XXXX-8452-E3F9", people[3], products[3], "Standard", "Revoked", dates[3]], ["XXXX-5207-F6A4", people[4], products[4], "Editorial", "Active", dates[4]]]) },
  activations: { title: "License Activations", description: "Monitor active devices and license activation activity.", metrics: [["Total Activations", "18,942", "+14.1%", "verification"], ["Active Devices", "15,284", "+11.8%", "check"], ["Revoked", "428", "-2.4%", "shield-minus"], ["This Month", "1,246", "+8.7%", "up"]], columns: ["Time", "User", "Product", "License Key", "Status", "Device", "Actions"], filters: ["All Status", "All Products"], rows: withActions(products.map((product, index) => [dates[index], people[index], product, `XXXX-XXXX-${1234 + index}`, index === 3 ? "Revoked" : "Active", ["Windows 11", "Windows 10", "MacOS 14", "Android 14", "iOS 18"][index]])) },
  "revoked-licenses": { title: "Revoked Licenses", description: "Review revoked licenses and the reasons access was removed.", metrics: [["Revoked Licenses", "428", "-2.4%", "shield-minus"], ["Fraud Related", "86", "+3.2%", "warning"], ["Refund Related", "214", "+1.1%", "rotate-ccw"], ["Manual Revocations", "128", "-4.3%", "user"]], columns: ["License Key", "User", "Product", "Reason", "Revoked By", "Revoked At", "Actions"], filters: ["All Reasons"], rows: withActions([["XXXX-XXXX-4588", people[0], products[0], "Refund issued", "System", dates[0]], ["XXXX-XXXX-6671", people[1], products[1], "Chargeback", "Admin", dates[1]], ["XXXX-XXXX-9012", people[2], products[2], "Duplicate account", "Admin", dates[2]], ["XXXX-XXXX-1124", people[3], products[3], "Fraud review", "System", dates[3]], ["XXXX-XXXX-3390", people[4], products[4], "User request", "Admin", dates[4]]]) },
  orders: { title: "Orders", description: "Review marketplace orders, payment status, and fulfillment.", metrics: [["Total Orders", "2,458", "+12.5%", "receipt"], ["Completed", "2,102", "+14.2%", "check"], ["Processing", "248", "+6.4%", "clock-9"], ["Refunded", "108", "-2.8%", "rotate-ccw"]], columns: ["Order", "Customer", "Product", "Amount", "Status", "Ordered At", "Actions"], filters: ["All Status"], rows: withActions(products.map((product, index) => [`#ORD-245${7 - index}`, people[index], product, `$${29 + index * 10}.00`, index === 2 ? "Processing" : index === 4 ? "Refunded" : "Completed", dates[index]])) },
  "download-links": { title: "Download Links", description: "Manage secure download links and access expiration across orders.", metrics: [["Active Links", "2,184", "+9.8%", "link"], ["Downloads Today", "1,246", "+15.4%", "download"], ["Expired Links", "328", "+2.1%", "clock-9"], ["Blocked Links", "42", "-3.6%", "shield-minus"]], columns: ["Link ID", "Order", "Product", "Customer", "Downloads", "Status", "Actions"], filters: ["All Status"], rows: withActions(products.map((product, index) => [`DL-${4821 + index}`, `#ORD-245${7 - index}`, product, people[index], `${index + 1} of 5`, index === 3 ? "Expired" : "Active"])) },
  analytics: { title: "Analytics", description: "Monitor marketplace performance, sales, and customer activity.", metrics: [["Gross Revenue", "$125,430.50", "+16.8%", "dollar"], ["Orders", "2,458", "+12.5%", "receipt"], ["Conversion Rate", "4.82%", "+0.6%", "up"], ["Avg. Order Value", "$51.03", "+3.2%", "dashboard"]], columns: ["Metric", "Current Period", "Previous Period", "Change", "Trend", "Updated", "Actions"], filters: ["All Trends"], rows: withActions([["Gross Revenue", "$125,430.50", "$107,350.20", "+16.8%", "Up", dates[0]], ["Orders", "2,458", "2,184", "+12.5%", "Up", dates[1]], ["Conversion Rate", "4.82%", "4.22%", "+0.6%", "Up", dates[2]], ["Refund Rate", "2.14%", "2.56%", "-0.42%", "Down", dates[3]], ["Active Customers", "1,286", "1,104", "+15.4%", "Up", dates[4]]]) },
};

function fallbackPage(section: string): PageConfig {
  const title = section.split("-").map((word) => word.charAt(0).toUpperCase() + word.slice(1)).join(" ");
  return {
    title,
    description: `Manage ${title.toLowerCase()} across the marketplace.`,
    metrics: [],
    columns: ["Name", "Description", "Status", "Updated", "Actions"],
    filters: ["All Status"],
    rows: withActions([[title, `Manage ${title.toLowerCase()} records`, "Active", "May 11, 2025"]]),
  };
}

export default function AdminTablePage({ section }: { section: AdminSection }) {
  const page = pages[section] ?? fallbackPage(section);
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState("All");
  const [currentPage, setCurrentPage] = useState(1);
  const pageSize = 3;
  const rows = page.rows.filter((row) => row.join(" ").toLowerCase().includes(search.toLowerCase()) && (filter === "All" || row.includes(filter)));
  const totalPages = Math.max(1, Math.ceil(rows.length / pageSize));
  const activePage = Math.min(currentPage, totalPages);
  const visibleRows = rows.slice((activePage - 1) * pageSize, activePage * pageSize);
  return <div className="mx-auto w-full max-w-[1400px]">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="mb-1 text-[10px] font-bold uppercase tracking-[0.1em] text-primary">Administration</p><h1 className="text-2xl font-bold tracking-tight text-heading sm:text-[28px]">{page.title}</h1><p className="mt-1 text-sm text-muted">{page.description}</p></div>{["users", "roles"].includes(section) && <button type="button" className="inline-flex items-center gap-2 rounded-lg bg-primary px-3 py-2 text-xs font-semibold text-white transition hover:bg-primary-hover"><PublicIcon name="add" className="h-3.5 w-3.5" /> Add {section === "users" ? "User" : "Role"}</button>}</header>
    {page.metrics.length > 0 && <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{page.metrics.map(([label, value, change, icon]) => <article key={label} className="rounded-xl border border-border bg-white p-4 shadow-sm"><div className="flex items-start justify-between"><p className="text-[10px] font-semibold text-muted-soft">{label}</p><span className="grid h-8 w-8 place-items-center rounded-lg bg-orange-50 text-primary"><PublicIcon name={icon} className="h-4 w-4" /></span></div><p className="mt-2 text-xl font-bold text-heading">{value}</p><p className={`mt-1 text-[9px] font-semibold ${change.startsWith("-") ? "text-status-danger" : "text-status-success"}`}>{change}</p></article>)}</div>}
    <section className={`${page.metrics.length > 0 ? "mt-5" : "mt-6"} overflow-visible rounded-2xl border border-border bg-white shadow-sm`}><div className="flex flex-col gap-3 border-b border-divider px-5 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div className="flex flex-1 flex-wrap gap-2"><label className="relative min-w-[14rem] flex-1 sm:max-w-[18rem]"><span className="sr-only">Search {page.title}</span><PublicIcon name="search" className="absolute left-3 top-2.5 h-4 w-4 text-muted-faint" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={`Search ${page.title.toLowerCase()}...`} className="h-9 w-full rounded-lg border border-border-control pl-9 pr-3 text-xs text-body outline-none placeholder:text-muted-faint focus:border-primary focus:ring-2 focus:ring-orange-100" /></label>{page.filters.map((name) => <select key={name} aria-label={name} value={filter} onChange={(event) => setFilter(event.target.value)} className="select-chevron h-9 rounded-lg border border-border-control bg-white px-3 pr-9 text-[10px] text-body outline-none transition hover:border-primary focus:border-primary focus:ring-2 focus:ring-orange-100"><option value="All">{name}</option><option>Active</option><option>Inactive</option><option>Verified</option><option>Pending</option><option>Approved</option><option>Resolved</option><option>Rejected</option><option>Suspended</option></select>)}</div></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="bg-surface-muted text-[10px] text-muted"><tr>{page.columns.map((column) => <th key={column} className="px-5 py-3 font-medium">{column}</th>)}</tr></thead><tbody>{visibleRows.map((row, rowIndex) => <tr key={`${row[0]}-${rowIndex}`} className="border-t border-divider text-body transition hover:bg-surface-hover">{row.map((value, valueIndex) => <td key={`${value}-${valueIndex}`} className={`px-5 py-3 ${valueIndex === 0 ? "font-medium text-body-strong" : "text-[10px] text-muted"}`}>{page.columns[valueIndex] === "Actions" ? <button type="button" aria-label={`More actions for ${row[0]}`} className="grid h-7 w-7 place-items-center rounded-md border border-border-action text-muted transition hover:border-primary hover:bg-accent-light hover:text-primary"><PublicIcon name="ellipsis-vertical" className="h-3.5 w-3.5" /></button> : ["Active", "Approved", "Resolved", "Verified"].includes(value) ? <Badge tone="success">{value}</Badge> : ["Pending", "In Review"].includes(value) ? <Badge tone="warning">{value}</Badge> : ["Inactive", "Suspended", "Expired", "Revoked", "Rejected"].includes(value) ? <Badge tone="danger">{value}</Badge> : value}</td>)}</tr>)}</tbody></table>{rows.length === 0 && <p className="px-6 py-12 text-center text-sm text-muted">No matching results.</p>}</div>
      <ProductPagination count={visibleRows.length} total={rows.length} page={activePage} pages={totalPages} itemLabel="records" onPageChange={setCurrentPage} />
    </section>
  </div>;
}


