const sequelize = require("./database");
const UserRole = require("./userRoleModel");
const UserInfo = require("./userModel");
const UserAccount = require("./userAccountModel");
const UserAccountRole = require("./userAccountRoleModel");
const OAuthAccount = require("./oauthAccountModel");
const CreatorProfile = require("./creatorProfileModel");
const Storefront = require("./storefrontModel");
const CreatorPayoutInfo = require("./creatorPayoutInfoModel");
const CardInfo = require("./cardInfoModel");
const Product = require("./productModel");
const ProductFile = require("./productFileModel");
const ProductPreview = require("./productPreviewModel");
const ProductVersion = require("./productVersionModel");
const Order = require("./orderModel");
const OrderItem = require("./orderItemModel");

if (sequelize) {
  UserInfo.hasOne(UserAccount, { foreignKey: "UserInfoId", as: "account" });
  UserAccount.belongsTo(UserInfo, { foreignKey: "UserInfoId", as: "info" });
  UserRole.hasMany(UserAccount, { foreignKey: "RoleId", as: "accounts" });
  UserAccount.belongsTo(UserRole, { foreignKey: "RoleId", as: "role" });
  UserAccount.hasMany(UserAccountRole, { foreignKey: "UserId", as: "roles" });
  UserRole.hasMany(UserAccountRole, { foreignKey: "UserRoleId", as: "userLinks" });
  UserAccountRole.belongsTo(UserAccount, { foreignKey: "UserId", as: "user" });
  UserAccountRole.belongsTo(UserRole, { foreignKey: "UserRoleId", as: "role" });
  UserAccount.hasMany(OAuthAccount, { foreignKey: "UserId", as: "oauthAccounts" });
  OAuthAccount.belongsTo(UserAccount, { foreignKey: "UserId", as: "account" });
  UserAccount.hasOne(CreatorProfile, { foreignKey: "UserId", as: "creatorProfile" });
  CreatorProfile.belongsTo(UserAccount, { foreignKey: "UserId", as: "user" });
  CreatorProfile.hasOne(Storefront, { foreignKey: "CreatorProfileId", as: "storefront" });
  Storefront.belongsTo(CreatorProfile, { foreignKey: "CreatorProfileId", as: "creatorProfile" });
  CreatorProfile.hasOne(CreatorPayoutInfo, { foreignKey: "CreatorProfileId", as: "payoutInfo" });
  CreatorPayoutInfo.belongsTo(CreatorProfile, { foreignKey: "CreatorProfileId", as: "creatorProfile" });
  CreatorProfile.hasMany(CardInfo, { foreignKey: "CreatorProfileId", as: "cardInfo" });
  CardInfo.belongsTo(CreatorProfile, { foreignKey: "CreatorProfileId", as: "creatorProfile" });
  Storefront.hasMany(Product, { foreignKey: "StorefrontId", as: "products" });
  Product.belongsTo(Storefront, { foreignKey: "StorefrontId", as: "storefront" });
  Product.hasMany(ProductPreview, { foreignKey: "ProductId", as: "previews" });
  ProductPreview.belongsTo(Product, { foreignKey: "ProductId", as: "product" });
  Product.hasMany(ProductFile, { foreignKey: "ProductId", as: "files" });
  ProductFile.belongsTo(Product, { foreignKey: "ProductId", as: "product" });
  Product.hasMany(ProductVersion, { foreignKey: "ProductId", as: "versions" });
  ProductVersion.belongsTo(Product, { foreignKey: "ProductId", as: "product" });
  ProductVersion.hasMany(ProductFile, { foreignKey: "ProductVersionId", as: "files" });
  ProductFile.belongsTo(ProductVersion, { foreignKey: "ProductVersionId", as: "version" });
  ProductVersion.hasMany(ProductPreview, { foreignKey: "ProductVersionId", as: "previewAssets" });
  ProductPreview.belongsTo(ProductVersion, { foreignKey: "ProductVersionId", as: "version" });
  Storefront.hasMany(OrderItem, { foreignKey: "StorefrontId", as: "orderItems" });
  OrderItem.belongsTo(Storefront, { foreignKey: "StorefrontId", as: "storefront" });
  Order.hasMany(OrderItem, { foreignKey: "OrderId", as: "items" });
  OrderItem.belongsTo(Order, { foreignKey: "OrderId", as: "order" });
}

module.exports = { sequelize, UserRole, UserInfo, UserAccount, UserAccountRole, OAuthAccount, CreatorProfile, Storefront, CreatorPayoutInfo, CardInfo, Product, ProductFile, ProductPreview, ProductVersion, Order, OrderItem };
